//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncampmentAnalyticsApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RegistrationDBEntities : DbContext
    {
        public RegistrationDBEntities()
            : base("name=RegistrationDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<getCountsByAgeAndStake_Result> getCountsByAgeAndStake()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCountsByAgeAndStake_Result>("getCountsByAgeAndStake");
        }
    
        public virtual ObjectResult<getCountsByAgeAndStakeAndWard_Result> getCountsByAgeAndStakeAndWard(Nullable<int> groupId)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCountsByAgeAndStakeAndWard_Result>("getCountsByAgeAndStakeAndWard", groupIdParameter);
        }
    
        public virtual ObjectResult<getListOfAttendees_Result> getListOfAttendees(Nullable<int> subgroupId)
        {
            var subgroupIdParameter = subgroupId.HasValue ?
                new ObjectParameter("SubgroupId", subgroupId) :
                new ObjectParameter("SubgroupId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getListOfAttendees_Result>("getListOfAttendees", subgroupIdParameter);
        }
    }
}
